### ISSUE TITLE
Compilation warning with the NuGet package

### ISSUE THREAD

**Issue by FrancescoBonizzi** [cyotek/Cyotek.Collections.Generic.CircularBuffer#15]
Hi and thanks for your work!

I installed the NuGet package of your library within a .NET Standard 2.0 project, and the compiler gives me this warning:

`Package 'Cyotek.CircularBuffer 1.0.3' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8' instead of the project target framework '.NETStandard,Version=v2.0'. This package may not be fully compatible with your project.`

![immagine](https://user-images.githubusercontent.com/11348479/101022350-94441b00-3571-11eb-8ca0-9daf813a22a2.png)

Reading the README.MD it seems that you library is fully compatible with .NET Standard 2.0!

Did I do something wrong?

Thanks!

**Comment by cyotek** [comment]
Hello,

Thanks for the question.

Version 1.0.3 and below only targets 2.0/3.5. The packages that currently properly target multiple platforms are marked as pre-release (the latest is https://www.nuget.org/packages/Cyotek.CircularBuffer/1.1.0-alpha6). You could try using one of those.

I had completely forgotten I hadn't published a version without a pre-release tag, I'll try and get to that this week.

Regards;
Richard Moss

**Comment by FrancescoBonizzi** [comment]
No problem at all! 
Thanks!
