### ISSUE TITLE
PeekLast(...,count) raises an IndexOutOfRangeException when buffer is overwritten

### ISSUE THREAD

**Issue by mmano** [cyotek/Cyotek.Collections.Generic.CircularBuffer#20]
Hi.
If buffer has room, the method works as expected (there is an unit test in the test suite for this use case).
But if some elements are overwritten, an exception occurs. (not covered in test suite).
In fact, the internal method ``GetTailIndex(i)`` is the culprit, producing some negative indexes.
On my side, an additional ``if (bufferIndex < 0) bufferIndex += _capacity;`` fixes the index value
```
  private int GetTailIndex(int index)
    {
      int bufferIndex;

      if (_tail == 0)
      {
        bufferIndex = _size - (index + 1);
      }
      else
      {
        bufferIndex = _tail - (index + 1);
        if (bufferIndex < 0) bufferIndex += _capacity;
      }

      return bufferIndex;
    }
```
On my side
```
      var buffer = new CircularBuffer<string>(5);
      buffer.Put(new[] { "a", "b", "c", "d", "e" });
      CollectionAssert.AreEqual(new[] { "d", "e" }, buffer.PeekLast(2));
      CollectionAssert.AreEqual(new[] { "a", "b" }, buffer.Peek(2));
  //overwrite
      buffer.Put(new[] { "f", "g" });
      CollectionAssert.AreEqual(new[] { "e", "f", "g"}, buffer.PeekLast(3));
      CollectionAssert.AreEqual(new[] { "c", "d", "e"}, buffer.Peek(3));
```

**Comment by cyotek** [comment]
Thanks for the contribution and apologies for how long it took me to respond.

I've published a new beta version (1.2.2) of the package incorporating your fix.

Thanks again for finding this bug and producing a test case and fix!

Regards;
Richard Moss
