### ISSUE TITLE
Usage for "number of messages per x" scenarios

### ISSUE THREAD

**Issue by Vaevictus** [cyotek/Cyotek.Collections.Generic.CircularBuffer#4]
Hi there,

I would like to know if your circular buffer could be used for the following situation:
-provide a count of objects "processed" in the last minute, hour or day
-be thread safe
How large do I size the buffer to address this? 24 * 60 * 60? so one per second?
When a message is processed, send it to the buffer (but send what exactly? the second?)
Queries to the buffer could be from multiple clients, possible at the same time.
Is that possible? 
Cheers

**Comment by cyotek** [comment]
Hello,

Thanks for the questions.

Firstly, the buffer isn't thread safe for either reading or writing - adding the extra overhead to support that wasn't required for my initial use of the library. Therefore, you would have to address this yourself, by ensuring anything calling the buffer performed appropriate locks etc. Probably would be nice if there was a thread safe variant of the class, but (for me) that would be a rainy day thing.

I'm not entirely sure that this is what you're looking for to be honest, it wasn't entirely designed for real time actions in the manner you seem to be describing, but more like a queue which overwrites old items if too many items are pushed into it.

Without knowing your exact requirements it's hard to say, but it seems to me you could get by with something much more simple if you just wanted to index by time.

Regards;
Richard Moss

**Comment by Vaevictus** [comment]
thanks for the reply, looks like this is not what I'm looking for unfortunately. Cheers.
