### ISSUE TITLE
Question to Skip() behavior

### ISSUE THREAD

**Issue by wongsyrone** [cyotek/Cyotek.Collections.Generic.CircularBuffer#5]
After `Skip(int count)`, should we reduce the element count of the circular buffer as well?

If I understand it correctly, it is intended to 'drop' some elements, which means the actual size of elements should be reduced to reflect that.

Feel free to correct me if I'm wrong.

**Comment by cyotek** [comment]
Hello,

Thanks for the report! Logically it makes sense that it should decrease the size, but the original code this library was based on allowed it to wrap. I "fixed" it locally and as expected, the new test I added passed, but the existing `SkipWrapBufferTest` failed.

While I'm not really sure what the intended use case for being able to skipping items but still being able to access them by cycling around the buffer is, I'm hesitant to break the functionality. Perhaps this would have to be a v2 breaking change. Alternatively, if no-one is using that functionality perhaps it would be fine to change.

Regards;
Richard Moss

**Comment by wongsyrone** [comment]
Okay. I just use `Get(int count)` and discard its returning data to 'skip' them.

**Comment by cyotek** [comment]
I was thinking about this again today and I'm starting to think the current behaviour is wrong and should be changed anyway.

Consider - you create a buffer with 10 elements. You push 5 elements, then decide to skip 2 The size is still 5, so if  you request 3 items all is well. But if you request the last two items... well, you're going to get uninitialised data. And depending on how you're processing the buffer, that could lead to subtle bugs.

So I'm now leaning more towards the idea of changing the behaviour.

**Comment by wongsyrone** [comment]
This is my final implementation of Skip(). You can get my idea from it.

```c#
public void Skip(int count)
{
    if (count < 0)
    {
        throw new ArgumentOutOfRangeException(nameof(count), "Negative count specified. Count must be positive.");
    }
    if (count > this.Size)
    {
        throw new ArgumentException("Ringbuffer contents insufficient for operation.", nameof(count));
    }

    // Modular division gives new offset position
    this.Head = (this.Head + count) % Capacity;
    this.Size -= count;
}
```

**Comment by cyotek** [comment]
Thanks for the feedback!

**Comment by wongsyrone** [comment]
You can improve Peek(), Get() and Put() performance by converting deep copy to something like Buffer.BlockCopy().

When I was using this lib for TCP stream buffering, Get/Put takes about 50ms, and drop to 6.3ms when re-write the blockcopy variant.

see also: https://github.com/xorxornop/RingBuffer
